version: "3.8"
services:
  containly:
    build: .
    image: cloudsmithy/containly
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
